---
- name: DEBIAN | Ensure sudo package is installed
  ansible.builtin.package:
    name: sudo
    state: present
    update_cache: true
  register: pkg_result
  retries: 12
  delay: 10
  until: pkg_result is success
